baseURL = "https://andreakomljenovic.github.io/"
theme = "minimal"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Calin Tataru"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Quicksand" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "CV"
    weight = 1

[[menu.main]]
    url = "/publications/"
    name = "Publications"
    weight = 2

[[menu.main]]
    url = "/software/"
    name = "Software"
    weight = 3

[[menu.main]]
    url = "/conferences/"
    name = "Conferences"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:andrea.komljenovic@meduniwien.ac.at"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/wirawara/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/antifreezeprot/"
    name = "twitter"
    weight = 3
